### ISSUE TITLE
Can not select gate

### ISSUE THREAD

**Issue by gabrielpan147** [embl-cba/bd-cellview#24]
Hello, I tried to process some images but I can not select gate. 
Here is the error log:

`[ERROR] org.scijava.module.MethodCallException: Error executing method: de.embl.cba.cellview.command.CellViewProcessorCommand#selectGateButtonCallback
	at org.scijava.module.MethodRef.execute(MethodRef.java:71)
	at org.scijava.module.AbstractModuleItem.callback(AbstractModuleItem.java:227)
	at org.scijava.widget.DefaultWidgetModel.callback(DefaultWidgetModel.java:179)
	at org.scijava.ui.swing.widget.SwingButtonWidget$1.actionPerformed(SwingButtonWidget.java:82)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.scijava.module.MethodRef.execute(MethodRef.java:67)
	... 39 more
Caused by: java.lang.NullPointerException
	at de.embl.cba.cellview.command.CellViewProcessorCommand.selectGateButtonCallback(CellViewProcessorCommand.java:265)
	... 43 more
`

**Comment by schraivo** [comment]
Can you share an example dataset (e.g. FCS file plus a few images)?

**Comment by tischi** [comment]
@gabrielpan147 thank you for getting in touch! 

As @schraivo pointed out a minimal example data set and an short description on when you clicked where (in which order) would be needed to debug this.

**Comment by gabrielpan147** [comment]
Thank you for your reply!
I have attached some of my demo data here. I try to mimic your data structure. since there is not a step by step instruction, I am not sure if I followed the correct data structure or miss any files. Please take a look and correct me if I'm wrong.
Thanks in advance!

[demo.zip](https://github.com/embl-cba/bd-cellview/files/13609354/demo.zip)

**Comment by schraivo** [comment]
Sorry for the delay, I've been on vacation (and sick afterwards). Here's a small dataset:

[pmaxGFP_small.zip](https://github.com/embl-cba/bd-cellview/files/13685405/pmaxGFP_small.zip)

**Comment by tischi** [comment]
@schraivo 

Your `reduced_gated` table contains `"` `"` surrounding each line.
This leads to an error when parsing the table.
I could invest time to change the code to handle this, but this is very non-standard, it would be better if you change your way of creating the table such that it does not contain the `"`.


```
"path	Cells	Single Cells	DRAQ7 neg	GFP pos"
"../images/00000000/HeLa RIEN pmaxGFP_00000000.tiff	FALSE	FALSE	FALSE	FALSE"
"../images/00000000/HeLa RIEN pmaxGFP_00000001.tiff	FALSE	FALSE	FALSE	FALSE"
"../images/00000000/HeLa RIEN pmaxGFP_00000002.tiff	FALSE	FALSE	FALSE	FALSE"
"../images/00000000/HeLa RIEN pmaxGFP_00000003.tiff	TRUE	TRUE	TRUE	FALSE"
"../images/00000000/HeLa RIEN pmaxGFP_00000004.tiff	TRUE	TRUE	TRUE	FALSE"
"../images/00000000/HeLa RIEN pmaxGFP_00000005.tiff	TRUE	TRUE	TRUE	FALSE"
"../images/00000000/HeLa RIEN pmaxGFP_00000006.tiff	TRUE	TRUE	TRUE	TRUE"
"../images/00000000/HeLa RIEN pmaxGFP_00000007.tiff	FALSE	FALSE	FALSE	FALSE"
"../images/00000000/HeLa RIEN pmaxGFP_00000008.tiff	FALSE	FALSE	FALSE	FALSE"
"../images/00000000/HeLa RIEN pmaxGFP_00000009.tiff	FALSE	FALSE	FALSE	FALSE"
"../images/00000000/HeLa RIEN pmaxGFP_00000010.tiff	FALSE	FALSE	FALSE	FALSE"
"../images/00000000/HeLa RIEN pmaxGFP_00000011.tiff	FALSE	FALSE	FALSE	FALSE"
"../images/00000000/HeLa RIEN pmaxGFP_00000012.tiff	FALSE	FALSE	FALSE	FALSE"
"../images/00000000/HeLa RIEN pmaxGFP_00000013.tiff	FALSE	FALSE	FALSE	FALSE"
"../images/00000000/HeLa RIEN pmaxGFP_00000014.tiff	FALSE	FALSE	FALSE	FALSE"
"../images/00000000/HeLa RIEN pmaxGFP_00000015.tiff	TRUE	TRUE	TRUE	FALSE"
"../images/00000000/HeLa RIEN pmaxGFP_00000016.tiff	TRUE	TRUE	TRUE	TRUE"
"../images/00000000/HeLa RIEN pmaxGFP_00000017.tiff	FALSE	FALSE	FALSE	FALSE"
"../images/00000000/HeLa RIEN pmaxGFP_00000018.tiff	FALSE	FALSE	FALSE	FALSE"
```

@gabrielpan147 in your case the `countpath.csv` table in principle works, but I had hard-coded in my code that the table must have more than 5 rows while yours only has 3 and thus it crashes.
Do you have a table with more rows to test with?

1. Open the table with `Add files….`
2. Select the table and gate using `Select gate`

**Comment by schraivo** [comment]
Tischi, can you use the following dataset? 
/g/bdimsort/testdata/pmaxGFP_small

**Comment by gabrielpan147** [comment]
Hi Tischi, 

Thank you for your testing! It is very interesting that the gating only works with more than 5 rows. Yes I have a larger test dataset, I will try it soon and let you know the result.

Thanks again!!
Gabriel

**Comment by gabrielpan147** [comment]
BTW, when using the plugins, is there a way to determine a scale bar of the image?

**Comment by schraivo** [comment]
> BTW, when using the plugins, is there a way to determine a scale bar of the image?

The scale bar can't be added within the tool. We didn't add this option since the scale bar is actually easier to add retrospectively (every image from ICS is 60 µm wide). The exception is when cropping images during image processing with our Fiji plugin (see the cropping option in our Fiji plugin), you need to know how many pixels you cropped left and right.

**Comment by gabrielpan147** [comment]
> > BTW, when using the plugins, is there a way to determine a scale bar of the image?
> 
> The scale bar can't be added within the tool. We didn't add this option since the scale bar is actually easier to add retrospectively (every image from ICS is 60 µm wide). The exception is when cropping images during image processing with our Fiji plugin (see the cropping option in our Fiji plugin), you need to know how many pixels you cropped left and right.

Thank you and happy New Year! Do you have any references that can cite the width of the ICS image? I did not find anything from their technical specifications.

**Comment by schraivo** [comment]
Yes, you can cite our science paper, we described it in that paper.On Jan 2, 2024, at 06:55, Gabriel PAN ***@***.***> wrote:﻿


BTW, when using the plugins, is there a way to determine a scale bar of the image?

The scale bar can't be added within the tool. We didn't add this option since the scale bar is actually easier to add retrospectively (every image from ICS is 60 µm wide). The exception is when cropping images during image processing with our Fiji plugin (see the cropping option in our Fiji plugin), you need to know how many pixels you cropped left and right.

Thank you and happy New Year! Do you have any references that can cite the width of the ICS image? I did not find anything from their technical specifications.

**Comment by tischi** [comment]
@gabrielpan147 can we close this issue?

**Comment by gabrielpan147** [comment]
@tischi yes sure, thank you again for your help!
